### ISSUE TITLE
Help me to develope DSDcc code

### ISSUE THREAD

**Issue by studentdsd** [f4exb/dsdcc#10]
Hello
I wanna modify the DSDcc or DSD source code for my university project. please tell me how can I able to compile these codes in visual studio C++ and what tools do i need ? 
Do you have any tutorial or document which show all necessary steps to compile these source codes in C/C++ programing environment ?

**Comment by f4exb** [comment]
Hello,

there is no VS C++ support at best you could try it to compile it with mingw in Windows. This is a cmake type of project so is pretty standard under Linux. You can easily figure it out by googling a bit. There are also instructions in the main readme.md that obviously you didn't even care to read before opening this issue.

Brgds.
