### ISSUE TITLE
dsdccx failed to replay/decode dmr_it_8.dis sample

### ISSUE THREAD

**Issue by shawnchain** [f4exb/dsdcc#11]
I have dsdccx compiled with mbelib enabled, and successfully decoded the ysf/dstar files under sample folder with command listed in the readme file, but no luck on DMR sample.

The command line used:

> sox -t s16 -r 48k -c 1 dmr_it_8.dis -t s16 -r 48k -c 1 - | dsdccx -T2 -i - -fa -o - | play -q -t s16 -r 8k -c 1 -

outputs: 

> ...
DSDDecoder::run: before processFrameInit: symbol 95339 (1675)
inlvl: 96% DSDDecoder::resetFrameSync: symbol 95392 (1571)
Sync:  +DMRd      DSDDecoder::run: good sync found: 10 symbol 95626 (11727)
DSDDecoder::run: before processFrameInit: symbol 95627 (1831)
inlvl: 101% DSDDecoder::resetFrameSync: symbol 95680 (2794)
No more input
End of process

OS:

> Darwin dev.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64

**Comment by f4exb** [comment]
It seems you don't get any output although the decoding takes place. This is typical of not compiling with the correct options. Make sure you have a cmake line like: `cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/dsdcc -DUSE_MBELIB=ON -DLIBMBE_INCLUDE_DIR=/opt/install/mbelib/include -DLIBMBE_LIBRARY=/opt/install/mbelib/lib/libmbe.so ..` in particular watch the `-DUSE_MBELIB=ON`

**Comment by f4exb** [comment]
Looks like a bug introduced in v1.7.4 (DMR negative). Obviously this is polluting normal DMR operation.

**Comment by shawnchain** [comment]
One more question, I would like to decode the MMDVM modem output frames with DSDCCX, any hints on that ?  it looks like a little bit off the topic, sorry :)

**Comment by f4exb** [comment]
Sorry dsdcc does not wotk on symbol input only sampled discriminator output.
