### ISSUE TITLE
lrrp support

### ISSUE THREAD

**Issue by jurek4321** [f4exb/dsdcc#12]
Can you add lrrp gps data decoding ?

**Comment by f4exb** [comment]
What is this ?

**Comment by jurek4321** [comment]
it should help with lrrp decoding https://forums.radioreference.com/voice-control-channel-decoding-software/323089-dsd-i-can-see-lrrp-ars-why-there-no-gps-positions.html its 3/4 data.

**Comment by f4exb** [comment]
For what it's worth there is something here written in Perl (ouch!): https://github.com/KD8EYF/TRBO-NET

**Comment by f4exb** [comment]
This is difficult to test and error prone so it will not be implemented.
