### ISSUE TITLE
Decrypt the decoded DMR voice

### ISSUE THREAD

**Issue by studentdsd** [f4exb/dsdcc#13]
Hello Sir,
I need to know your opinion about decryption DMR voice. Do you think it is possible to add a function to your code which able to decrypt DMR ? Have you ever considered this property for next version of program?
Added to this, I have several question about DMR code in your project and related error. I ask you to guide me Where do I put these questions?
Thanks.

**Comment by f4exb** [comment]
Hi,

I don't  know if there is a standard way to decrypt voice data. Need to check the ETSI standard. If so the encryption algorithm would be known and it may be possible if the user provides the encryption key. I do not intend to allow hacking the encryption key using this software.
Can you be more precise about the "error" you get?

Brgds.

**Comment by studentdsd** [comment]
Thanks for your helpful answer.
It is not really error, I just tried to decode a DMR sample by using sox form this site: https://www.sigidwiki.com/wiki/Digital_Mobile_Radio_(DMR) but it seems I need to set specific parameters to decode it. Do you have any suggestion?
I decoded it by means of ِDSD by using SDR# and Cubicsdr because the DSD is not able to demodulate NFM.

**Comment by f4exb** [comment]
The typical command is listed here: https://github.com/f4exb/dsdcc#running

**Comment by f4exb** [comment]
Actually it is easy to convert to single channel (mono) using sox.

**Comment by ounismohamed** [comment]
@f4exb Sir , can i understand the reason of the cause of the "cach ERR " and why there is no decoding ,the health of the signal is good for sure 
![2](https://user-images.githubusercontent.com/35819408/44292955-d56c7000-a27f-11e8-81c7-7d75f8ea068b.PNG)
![1](https://user-images.githubusercontent.com/35819408/44292957-d56c7000-a27f-11e8-9efd-d86c251c109e.PNG)

**Comment by f4exb** [comment]
As I understand from the screenshot you're talking about DSD+ here not DSDcc so your question is out of subject.
