### ISSUE TITLE
High pitch tone

### ISSUE THREAD

**Issue by sv1** [f4exb/dsdcc#2]
I am trying now for a couple of days to make dsdccx work on a Debian 8.0 system. Whatever settings I have used in order to decode d-star transmissions fail. All I hear is a high pitch tone on my speakers!!!

Any idea what could cause this?

**Comment by f4exb** [comment]
Hello,

can you please try with one of the provided samples? Assuming your current directory is the root of the cloned repository and dsdccx is in the path (adapt to your needs):

sox -t s16 -r 48k -c 1 samples/dstar_f1zil_1.dis -t s16 -r 48k -c 1 - | dsdccx -i - -fa -o - | play -q -t s16 -r 8k -c 1 -

Of course sox must be installed (sudo apt-get install sox).

You should hear a fragment of conversation in French.

Best regards.

**Comment by sv1** [comment]
Hello,

I have tried the samples but instead of conversation all I hear is a
high pitch tone!!!

thanks.

**Comment by f4exb** [comment]
Please make sure you type the command exactly as it is written. Output is at 8k so if the system default of 48k is used for audio the pitch will be 6x higher than original.

**Comment by sv1** [comment]
Hello,

I have copy&paste the command in order to avoid typing errors. All I get
is a tone. No audio is decoded.

$ sox -t s16 -r 48k -c 1 samples/dstar_f1zil_1.dis -t s16 -r 48k -c 1 -
| dsdccx -i - -fa -o - | play -qt s16 -r 8k -c 1 -
DSDDstar::reset_header_strings
DSDDecoder::resetFrameSync: symbol 0 (0)
Digital Speech Decoder DSDcc
Enabling auto frame decoding.
Opened - for input.
Opened - for output.
DSDDecoder::run: invalid sync found: -1 symbol 1800 (16182)
DSDDecoder::resetFrameSync: symbol 1800 (16182)
DSDDecoder::run: invalid sync found: -1 symbol 3600 (24385)
DSDDecoder::resetFrameSync: symbol 3600 (24385)
DSDDecoder::run: invalid sync found: -1 symbol 5400 (2531)
DSDDecoder::resetFrameSync: symbol 5400 (2531)
DSDDecoder::run: invalid sync found: -1 symbol 7200 (3891)
DSDDecoder::resetFrameSync: symbol 7200 (3891)
Sync:  -D-STAR_HD    DSDDecoder::run: good sync found: 19 symbol 7622
(-13063)
DSDDecoder::run: before processFrameInit: symbol 7623 (-11357)
inlvl: 66% DSDDstar::reset_header_strings

DSTAR HEADER: RPT 2: F1ZIL  B RPT 1: F1ZIL  B YOUR: CQCQCQ   MY:
F1NSR   /ID51
e:
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 

If this helps I ran also dsdccx without piping the output to sox and it
doesn't seems right....

$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX
$ABCDEFGHIJKLMNOPQRSTUVWX$

**Comment by f4exb** [comment]
There may be some memory pointer corruption somewhere. the string "ABCDEFGHIJKLMNOPQRSTUVWX$ABCDEFGHIJKLMNOPQRSTUVWX" appears only in locator.cpp:

std::string const Locator::m_lon_array3 = "ABCDEFGHIJKLMNOPQRSTUVWX";
std::string const Locator::m_lat_array3 = "ABCDEFGHIJKLMNOPQRSTUVWX";

This is the Maidenhead locator calculator and there is no valid reason this string should be found on the audio output!

However I am unable to reproduce.

**Comment by f4exb** [comment]
In fact there is a problem if you specify -DUSE_MBELIB=ON but mbelib is not found. I am not sure the find mbelib macro works correctly.

**Comment by f4exb** [comment]
It appears there is a problem when compiling in release mode

**Comment by f4exb** [comment]
Can you please try the latest version or install the .deb package here: https://github.com/f4exb/dsdcc/releases/tag/v1.6.0

I tried the binary installed from the package and I don have a problem anymore.

**Comment by sv1** [comment]
Hello,

I have tried the binary on Debian 8.6 but due to dependencies error I
can not use it:

$ sudo dpkg -i /tmp/dsdcc_1.6.0-1_amd64.deb 
Selecting previously unselected package dsdcc.
(Reading database ... 321337 files and directories currently installed.)
Preparing to unpack /tmp/dsdcc_1.6.0-1_amd64.deb ...
Unpacking dsdcc (1.6.0-1) ...
dpkg: dependency problems prevent configuration of dsdcc:
dsdcc depends on libstdc++6 (>= 5.2); however:
  Version of libstdc++6:amd64 on system is 4.9.2-10.

dpkg: error processing package dsdcc (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
dsdcc

Also tried to build it through "git clone..."

Now I do not get the tone.... but I do not have audio at all.

DSDDstar::reset_header_strings
DSDDecoder::resetFrameSync: symbol 0 (0)
Digital Speech Decoder DSDcc
Set data rate to 4800 bauds. 10 samples per symbol
Enabling the decoding of D-Star frames.
Opened - for input.
Opened - for output.
DSDDecoder::run: invalid sync found: -1 symbol 1800 (-12259)
DSDDecoder::resetFrameSync: symbol 1800 (-12259)
DSDDecoder::run: invalid sync found: -1 symbol 3600 (18477)
DSDDecoder::resetFrameSync: symbol 3600 (18477)
DSDDecoder::run: invalid sync found: -1 symbol 5400 (18948)
DSDDecoder::resetFrameSync: symbol 5400 (18948)
DSDDecoder::run: invalid sync found: -1 symbol 7200 (1109)
DSDDecoder::resetFrameSync: symbol 7200 (1109)
Sync:  -D-STAR_HD    DSDDecoder::run: good sync found: 19 symbol 7641
(-13063)
DSDDecoder::run: before processFrameInit: symbol 7642 (-11357)
inlvl: 66% DSDDstar::reset_header_strings

DSTAR HEADER: RPT 2: F1ZIL  B RPT 1: F1ZIL  B YOUR: CQCQCQ   MY:
F1NSR   /ID51
e:
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 
MBE: 

73
Apostolos

**Comment by f4exb** [comment]
Assuming mbelib is installed in /opt/install/mbelib and you install dsdcc in /opt/install/dsdcc the cmake command should be:

cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/dsdcc -DUSE_MBELIB=ON -DLIBMBE_INCLUDE_DIR=/opt/install/mbelib/include -DLIBMBE_LIBRARY=/opt/install/mbelib/lib/libmbe.so ..

If you have no sound it looks like it was not compiled with mbelib support. A sign is also that if you don't have mbelib support the "MBE:" lines scroll very fast (it is not paced with actual audio).

**Comment by sv1** [comment]
Hello,

although the cmake script found the mbelib, it is not compiled by
default.

Using -DUSE_MBELIB=ON work as expected!!!


Thank you very much!!!

73
Apostolos




On Δευ, 2017-01-16 at 01:39 -0800, f4exb wrote:
> Assuming mbelib is installed in /opt/install/mbelib and you install
> dsdcc in /opt/install/dsdcc the cmake command should be:
> 
> cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/dsdcc
> -DUSE_MBELIB=ON -DLIBMBE_INCLUDE_DIR=/opt/install/mbelib/include
> -DLIBMBE_LIBRARY=/opt/install/mbelib/lib/libmbe.so ..
> 
> If you have no sound it looks like it was not compiled with mbelib
> support. A sign is also that if you don't have mbelib support the
> "MBE:" lines scroll very fast (it is not paced with actual audio).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the
> thread.Web Bug from
> https://github.com/notifications/beacon/AFRSQ8ukLLBC1rjK98t_I4QgcbGY_xD5ks5rSzrhgaJpZM4Lb8hF.gif
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/f4exb/dsdcc","title":"f4exb/dsdcc","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/f4exb/dsdcc"}},"updates":{"snippets":[{"icon":"PERSON","message":"@f4exb in #2: Assuming mbelib is installed in /opt/install/mbelib and you install dsdcc in /opt/install/dsdcc the cmake command should be:\r\n\r\ncmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/dsdcc -DUSE_MBELIB=ON -DLIBMBE_INCLUDE_DIR=/opt/install/mbelib/include -DLIBMBE_LIBRARY=/opt/install/mbelib/lib/libmbe.so ..\r\n\r\nIf you have no sound it looks like it was not compiled with mbelib support. A sign is also that if you don't have mbelib support the \"MBE:\" lines scroll very fast (it is not paced with actual audio)."}],"action":{"name":"View Issue","url":"https://github.com/f4exb/dsdcc/issues/2#issuecomment-272814127"}}}

-- 
Κεφάλας Απόστολος -  SV1LJJ 

τηλ: +30 6979 976 039
Echolink id: 309275
skype: apostolis.kef
sip:apkefalas@iptel.org
PGP: 0xA3C19DA0

**Comment by f4exb** [comment]
Well originally I wanted to make sure people understand the controversial views about possible copyright infringements of mbelib and make the final decision.

However the Debian package just embeds mbelib for convenience.

So if it now works I think we can say release v1.6.0 fixes the problem.
