### ISSUE TITLE
Can't build from source

### ISSUE THREAD

**Issue by febs** [f4exb/dsdcc#25]
I am following [the instructions on the sdrangel page](https://github.com/f4exb/sdrangel/wiki/Compile-from-source-in-Linux) to build this required library. 

When it's time of dsdcc I get this.

`No rule to make target '/opt/install/serialdv/lib/libserialdv.so', needed by 'libdsdcc.so'.  Stop.`

I am on Ubuntu Ubuntu 19.04 and ran the prerequisite apt command to install the necessary package.

Thank you

**Comment by f4exb** [comment]
`CMakeLists.txt` checks are weaker on `dsdcc` than on `sdrangel`. If you tell it `serialdv` is in `/opt/istall/serialdv`then it will trust it even if it is not there and let `cmake` pass. However you get an error at compile time. Solution is to build and install serialdv in `/opt/install/serialdv`before compiling `dsdcc`.
