### ISSUE TITLE
P25 decoding

### ISSUE THREAD

**Issue by nostar** [f4exb/dsdcc#26]
I saw this issue at the SDRAngel repo:

https://github.com/f4exb/sdrangel/issues/195

I added the issue here, since it looks like it was never added over here.  I would also love to see P25 decoding support in DSDcc/SDRAngel, then it would be the single solution for everything.  Currently I switch to GQRX piped into DSD for P25 decoding.

A good place to get P25 traffic on your PiStar is the 420 p25.evsuperfreqs.com reflector.  Its very active since its a P25/YSF/DMR/NXDN multimode.  This also lets you transmit on one of the other modes and get P25 output when desired when you don't have a P25 radio.

**Comment by sysardex** [comment]
Is there any progress planned on this issue?

**Comment by aschuhardt** [comment]
Is this still unsupported?

**Comment by f4exb** [comment]
Sorry no more new developments on dsdcc
