### ISSUE TITLE
dsdccx uses in_file and out_file without initializing it

### ISSUE THREAD

**Issue by df7cb** [f4exb/dsdcc#28]
Invoking dsdccx without arguments produces this:
```
DSDDstar::reset_header_strings
DSDDecoder::resetFrameSync: symbol 0 (0)
Digital Speech Decoder DSDcc
Cannot open @Ò~Hþ for input. Aborting
```

(cm256_{rx,test,tx} seem to have the same problem, fwiw.)

**Comment by df7cb** [comment]
This is still a bug.

**Comment by gr8lite** [comment]
I could use some help with this.
I get input and output open and hear sound from virtual_port, but dsdccx makes no indication that is is hearing/decoding any signals at all.
It seems as if dsdccx i
s not picking up the stream.
Have virtual_sink in PA setup and vitual-sink selected in apps audio.
Any suggestion for strings that will work better.
