### ISSUE TITLE
DSD back compatibility ?

### ISSUE THREAD

**Issue by samysousa** [f4exb/dsdcc#32]
Not sure where it is appropriate to ask the question.

**Is dsdcc compatible with dsd ?**
can i just rename /usr/local/bin/dsdcc to /usr/local/bin/dsd and possibly any integration already using dsd would still function ?

**It would be a good addition to the documentation or Readme.md to make this clear:**

- If dsdcc can act as replacement for dsd
- In what capacity could dsdcc be compiled in a way that replaces/updates dsd usage. (Particulary if it`s just outputting audio then it should be capable of being an updated replacement.
- where would it be not recommended to do this ? or is is simply recommended to not do this.

Or Something in the Wiki for the project.

Regards,
Sam

**Comment by f4exb** [comment]
**Is dsdcc compatible with dsd ?**
No

**t would be a good addition to the documentation or Readme.md to make this clear:**
What is not clear in https://github.com/f4exb/dsdcc#dsdcc ?
