### ISSUE TITLE
What exactly does dsdcc want as input ?

### ISSUE THREAD

**Issue by righthalfplane** [f4exb/dsdcc#37]
I have looked for the answer and I found one comment 15 kHz NBFM.  The program decimates the input to a bandwidth of 15 kHz, decodes it as FM, then interpolates to bandwidth of 48 kHz and scales the data to a 16 bit signed integer - this decodes NBFM speech perfectly. It processes the data in blocks of 4800 S16LE (i.e. 1/10 of a second) and writes out the blocks.  Is that what dddcc wants ?  I get parts of words it seems to translate about 1 out of 10 of the blocks. I am scanning and trying to decode the P25 channels that my IC-R30 decodes nicely.

**Comment by nivex** [comment]
According to the help text, P25 decoding is not supported by dsdcc.
