### ISSUE TITLE
Error writing to output

### ISSUE THREAD

**Issue by brovary3154** [f4exb/dsdcc#4]
I get the "Error writing to output" repeatedly if not using the ambe3000 dongle.

My usage, that reports this error:
rtl_fm -f 441.00000M -M fm -g 100 -s 70K -r 48K -E dc - | dsdccx -fr -i - -o - -U 0 -g 50 | play -q -t s16 -r 8k -c 1 - 

Works fine when using a dongle:
rtl_fm -f 441.00000M-M fm -g 50 -s 70K -r 48K -E dc - | dsdccx -fr -i - -o - -D /dev/ttyUSB0 -g 50 | aplay -f S16_LE -	

I did the cmake -DUSE_MBELIB=ON ..

**Comment by f4exb** [comment]
Hello,

I guess you compiled without mbelib support hence when not using the dongle it defaults to mbelib. Without mbelib support it does not break but no samples come out which ends up the rather cryptic message you see. Did you try one of the binary packages that have mbelib built in?

To activate mbelib support during compilation you have to use -DUSE_MBELIB=ON on the command line and if mbelib is not installed in the usual directories (/usr/...) you have to specify paths to includes and lib using -DLIBMBE_INCLUDE_DIR=... -DLIBMBE_LIBRARY=.../libmbe.so (... is whatever suits your installation).

Best regards.
