### ISSUE TITLE
Show callsigns for decoded YSF and other modes

### ISSUE THREAD

**Issue by dranch** [f4exb/dsdcc#40]
I have been successful in decoding and listening to the DMR and Dstar examples found in this great tool's "samples/" directory but I found the Yaesu System Fusion example is 100% garbled and/or plays static.  To work around this, I tried decoding some local traffic captured from a Kenwood D710's 1200baud data pin into a soundcard but nothing decoded.  I then tried saving some audio files via Gqrx v2.6 with an Airspy R2 SDR and that worked fine.  I used the following command to get full decoded voice audio:

   sox -t s16 -r 48k -L -c 2  gqrx_record-ww6bay-k2wbb-kb5dlx-qso-dr1.wav -t s16 -r 48k -c 1 - | ./dsdccx -v5 -i - -fy -o - 2>/tmp/stderr.txt | play -q -t s16 -r 8k -c 1 -

Unfortunately, no callsigns are seen in the /tmp/stderr.txt file which is something I'm specifically looking for.  I DO once callsign decode in the Dstar example file:

   samples/dstar_f1zil_1.dis
   DSTAR HEADER: RPT 2: F1ZIL  B RPT 1: F1ZIL  B YOUR: CQCQCQ   MY: F1NSR   /ID51

No callsigns are seen in the the DMR decode.  Actually, I do see an attempted Dstar decode for the DMR example which seems like a bug in the tool as why would a DMR decode be showing Dstar info lines?

   DSTAR HEADER: RPT 2: څ<94>^?[.tH RPT 1: ^]<A6>S<9A>T<C5><EE><FD> YOUR:  <A4><A4><C5><FA><B2><EA><A4> MY: }$<C8><D2>^_<EF><8E><F6>/<DF>q(<D0>

Anyway, is showing callsigns supported in dsdcc?  If not, could it be added?  Sure would be useful!

--David
KI6ZHD

**Comment by f4exb** [comment]
DMR does not support amateur radio callsigns. It is a professional radio communications protocol unlike D-Star (or YSF) that is amateur radio oriented. 

If the signal is too noisy some signature sequence can be recognized as D-Star although it is not. There is no way to circumvent this apart from discarding  too weak signals or forcing single mode (`-f` option).
