### ISSUE TITLE
Golay(24,12) decodong error

### ISSUE THREAD

**Issue by com1313** [f4exb/dsdcc#41]
Hello! I founded, thay golay(24,12) doesn't correct errors, if error occur in the integrity bits.
Example 1: 12 data bits / 12 integrity bits. Add 3 error in data[0], data[1], data[2] -> correcct all 3 errors. 
Example 2: 12 data bits / 12 integrity bits. Add 3 error in data[0], data[1], integrity[0] -> doesn't correcct.

**Comment by f4exb** [comment]
It looks like there is an issue with the syndrome look up table because it covers only bit flips occurring in the message part. The issue possibly extends to codes based on the same algorithm.

**Comment by f4exb** [comment]
Other codes affected:
  - Golay(20,8)
  - Golay(23,12)

**Comment by f4exb** [comment]
DMR and dPMR are affected and could benefit from the fix.

**Comment by f4exb** [comment]
Implemented in v1.9.1
