### ISSUE TITLE
Decoding noise and outputing garbled audio.

### ISSUE THREAD

**Issue by zAlex01** [f4exb/dsdcc#44]
https://youtu.be/FHfbLevnw1I
DSD is identifying noise as digital signal and outputing distorted audio.
I tried installing it both through pacman and compiling it myself with the same result.

**Comment by iScottybotty** [comment]
If your decoding moto BP, or trying too, it WONT work. The developer also to my understanding wants nothing more to do with it either. 

All the necessary is in the Louis Harve version, but again, the BP decoder isn’t released in the public version. 

Scott.

**Comment by zAlex01** [comment]
> If your decoding moto BP, or trying too, it WONT work. The developer also to my understanding wants nothing more to do with it either. All the necessary is in the Louis Harve version, but again, the BP decoder isn’t released in the public version. Scott.
> […](#)
> On 14 Nov 2021, at 09:38, Alex ***@***.***> wrote: ﻿ Closed #44. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I understand this. However, that's not the issue I'm facing right now. I can tune in to a random frequency with nothing being transmitted and on the terminal output it looks like it's detecting a digital signal and it will start outputing distorted audio.
