### ISSUE TITLE
Jolie démodulateur faites-le fonctionner avec un meilleur graphique s'il vous plaît de plus en plus je viens .

### ISSUE THREAD

**Issue by alexandregaspar** [f4exb/dsdcc#53]
Le démodulateur je veux que le graphique soit une un peu modifié avec un graphique qui soit joli et agréable au visuel si vous pouvez en créer un ça ça serait intéressant dans l'évolution j'ai vu que vous pouvez trouver des cryptage spécialisés aussi pour les radios amateurs. J'ai vu la fontaine beaucoup plus jolie sur le graphique mais je voudrais aussi que le décodeur soit beaucoup plus joli graphiquement si possible si vous ne pouvez pas ce n'est pas grave mais ça m'intéresse et j'aime bien votre DSD j'ai pu avoir beaucoup de décodeur que je que j'ai eu. 👍🗣️

**Comment by f4exb** [comment]
dsdcc is a commmand line tool so this is off topic. Moreover issues and comments should be written in English.

**Comment by alexandregaspar** [comment]
I'm interested in double, in voice, in cryptocurrency.
