### ISSUE TITLE
How handle inverted dmr signal

### ISSUE THREAD

**Issue by moeinkarimi1984** [f4exb/dsdcc#7]
hi
thanks for code
How does this code deal with inverted-dmr signals.
i compared code with dsd and some changes seen here.
for example in dsd if inverted option selected dibit inverted when necessary, but in your code there is no option for inverted signal on dmr.
First, there is a decoding of the inverted-dmr signal in this code?
thanks

**Comment by f4exb** [comment]
Hello,
in fact the program tries every possible preamble signature it knows and therefore if the baud rate is set right (4800 for DMR) it will detect the mode automatically. While doing so it also tries the sequence with inverted symbols and therefore is able to detect if the mode is inverted or not. 
Let me know if this does not work as expected.
Best regards.
