### ISSUE TITLE
Pls implement DMR negative

### ISSUE THREAD

**Issue by wb2vwi** [f4exb/dsdcc#9]
can you implement dmr cc negative polarity  which is used in mototurbo network currently it is not supported

**Comment by f4exb** [comment]
Indeed this is missing. See: https://github.com/f4exb/dsdcc/blob/master/dsd_decoder.h#L102

**Comment by f4exb** [comment]
Done in v1.7.5

**Comment by wb2vwi** [comment]
-dmrv is still not autodetecting in dsd decoder

**Comment by f4exb** [comment]
Can you please provide a sample or access to a sample? There are no DMR negative transmissions around here.

**Comment by f4exb** [comment]
Reverted in v1.7.7
